version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 199299155478.dkr.ecr.us-east-2.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      # Replace with your application name
      - APPLICATION_NAME=fabiopinho-ecs-api-java
      - REPOSITORY_URI=199299155478.dkr.ecr.us-east-2.amazonaws.com/$APPLICATION_NAME
  build:
    commands:
      - echo Build started on 'date'
      - echo Building the Docker image...
      - mvn --quiet install
      - docker build -t $APPLICATION_NAME:$IMAGE_TAG .
      - docker tag $APPLICATION_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build started on 'date'
      - echo pushing to repo
      - echo Building the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo writing image definitions file...
      # Give your container name
      - printf '[{"name":"SpringBootAppContainer", imageUri}:"%s"]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo printing imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
